### ISSUE TITLE
When “Extracting grayscale images”, the values of the y-axis are reversed

### ISSUE THREAD

**Issue by moroth89** [localdevices/pyorc#168]
****************************************
hi, 
I have the following problem: When I execute the command: da[0].frames.plot(cmap=“gray”, ax=ax) the direction of the y-axis is reversed (see images below). 
![ARRC_stabilized-area](https://github.com/localdevices/pyorc/assets/59596749/931fcee4-0594-4ad0-9c13-e20e6f729a62)
![ARRC_grey](https://github.com/localdevices/pyorc/assets/59596749/bd9fa7f2-ba6d-4a4e-922b-3e2c98e8f23f)
Is it possible that there is a bug?

I have attached the video and the case file here.
[https://gigamove.rwth-aachen.de/de/download/ffb0e0c743ad1785a07901934411e53f](url)

Thanks a lot in advance. 

Best, 
Moritz

****************************************
### How did you install pyopenrivercam (mamba / conda or  pip)

[mamba]

### What is the problem?

[When “Extracting grayscale images”, the values of the y-axis are reversed]

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a video, if possible include a copy of your dataset uploaded on Dropbox, Google Drive, or other)

[Type answer here]

**Comment by hcwinsemius** [comment]
Hello @moroth89 . This is by design. The control point coordinates are stored in the original row and column coordinates of the frames which are descending order for the row-coordinates. The `frames` module only uses ascending coordinate axes whether dealing with unprotected frames, or projected frames. Hence to combine the camera config coordinates with a plot with frames you can simply use the normal `matplotlib.pyplot.imshow` function to plot a single frame, and then add the camera config on the same axis.

**Comment by moroth89** [comment]
Yes, that's exactly how I came up with a solution. Thank you for your answer anyway. Problem solved.
